#!/bin/bash

# 1. Create the Vault folder
sudo mkdir -p /opt/Bashrot_vault

# 2. Set the "Standard" locks (The Owners)
# We make 'root' the owner and 'wardens' the group owner
sudo chown root:wardens /opt/Bashrot_vault
sudo chmod 770 /opt/Bashrot_vault

# 3. Use ACLs for "Extra" permissions
# Give guards full power (rwx)
sudo setfacl -m g:guards:rwx /opt/Bashrot_vault
# Make sure bashers are BLOCKED from the main vault
sudo setfacl -m g:bashers:--x /opt/Bashrot_vault

# 4. Create the "Secret Tunnel" (The Vulnerability)
sudo mkdir -p /opt/Bashrot_vault/.secret_tunnel
# Give bashers ONLY 'execute' (x) permission
# This means they can 'cd' into it if they know the name, 
# but they can't 'ls' to see what's inside!
sudo setfacl -m g:bashers:--x /opt/Bashrot_vault/.secret_tunnel

echo "The Vault is secured... and the trap is set."
